[flags]
basic = true
hide_k_threads = true
enable_cache_memory = true
regex = true
process_memory_as_value = true
default_widget_type = "proc"
network_use_binary_prefix = true
average_cpu_row = true

[styles]
theme = "nord"

[styles.widgets]
border_color = "darkgray"
selected_border_color = "black"
widget_title = { color = "cyan", bold = true }
selected_text = { bg_color = "darkgray", color = "gray" }
text = { color = "gray" }

[styles.tables]
headers = { color = "cyan" }

[styles.memory]
ram_color = "yellow"
cache_color = "green"

[styles.network]
rx_color = "lightblue"
tx_color = "lightcyan"
rx_total_color = "blue"
tx_total_color = "cyan"

[styles.cpu]
avg_entry_color = "white"
cpu_core_colors = [
    "magenta",
    "blue",
    "lightblue",
    "cyan",
    "green",
    "yellow",
    "lightred",
    "red",
]

[disk.mount_filter]
list = ["/boot/efi", "/var/log", "/var/cache"]

[processes]
columns = [ "PID", "Name", "CPU%", "Mem%", "GPU%", "GMem%", "User", "State", "Time"]
