# vim: ft=kitty
env KITTY_THEME=dark

foreground              #ECEFF4
background              #2E3440

color0                  #2E3440
color8                  #4C566A
color1                  #BF616A
color9                  #D08770
color2                  #A3BE8C
color10                 #A3BE8C
color3                  #EBCB8B
color11                 #EBCB8B
color4                  #5E81AC
color12                 #81A1C1
color5                  #B48EAD
color13                 #9A8AAC
color6                  #8FBCBB
color14                 #88C0D0
color7                  #ECEFF4
color15                 #D8DEE9

selection_foreground    #ECEFF4 
selection_background    #4C566A

tab_bar_background      #2E3440
active_tab_foreground   #2E3440
active_tab_background   #8FBCBB
inactive_tab_foreground #D8DEE9
inactive_tab_background #4C566A

scrollbar_handle_color  #4C566A
scrollbar_track_color   #2e3440

url_color               #5E81AC
active_border_color     #4C566A
inactive_border_color   #4C566A
bell_border_color       #BF616A
