# vim: ft=kitty

font_size 12.0
# leave a bit more space between lines
modify_font cell_height +8px

# Regular text: FiraCode Mono
font_family  FiraCodeNFM-Reg
# bold_font    FiraCodeNFM-SemBd

# zero with dot, =~ and !~ operators, different @ sign
# see https://github.com/tonsky/FiraCode#:~:text=variants
font_features FiraCodeNFM-Reg +zero +ss07 +ss05
font_features FiraCodeNFM-SemBd +zero +ss07 +ss05

# Italics: JetBrainsMono, it fits well with Fira Code
italic_font      JetBrainsMonoNF-Italic
bold_italic_font JetBrainsMonoNF-BoldItalic
