protocol file 
mime image/*
action launch --type=overlay --title "Image" kitten icat --hold ${FILE_PATH}

protocol file
mime text/*
action launch --type=overlay ${EDITOR} -- ${FILE_PATH}

protocol file
mime inode/*
action launch --type=overlay zsh -ic lf -- ${FILE_PATH}
