# vim: ft=kitty

dynamic_background_opacity yes
# There doesn't seem to be a way to set them per-theme for now
transparent_background_colors #E5E9F0 #D8DEE9 #C0C7D5 #4c566a #353c4A

# Dark theme by default, can be changed on demand using C-Esc [dl]
include dark.conf

# Fonts
include fira_code.conf
# include iosevka.conf
# always use `fira code nf` for nerd symbols, it looks better
symbol_map U+E000-U+F8FF,U+F0000-U+FFFFF,U+100000-U+10ffff FiraCodeNFM-Reg

disable_ligatures cursor

# Cursor 
cursor none
cursor_text_color background
cursor_shape underline
cursor_underline_thickness 1
cursor_beam_thickness 1.5

# Layouts
enabled_layouts splits:split_axis=auto

# The Bell
enable_audio_bell no
bell_path /usr/share/sounds/freedesktop/stereo/dialog-warning.oga

tab_bar_style hidden

# the window
window_padding_width 2
