#!/usr/bin/env bash

if ! out="$(yad --title="Play from MPD" --form \
    --field=Track '' \
    --field=Artist '' \
    --field=Album '' \
    --field=Genre '' \
    --field=Shuffle:CHK TRUE \
    --field=Append:CHK FALSE \
    --buttons-layout=edge --button=Play:0 --button=Abort:1)"; then
    exit
fi

IFS="|" read -r track artist album genre shuffle append <<<"$out"
if [[ "$append" != TRUE ]]; then
    mpc clear
fi
mpc search title "$track" artist "$artist" album "$album" genre "$genre" | mpc add
playerctl stop
if [[ "$shuffle" == TRUE ]]; then
    mpc shuffle
fi
mpc play
