#!/usr/bin/env bash

DATEFMT="%Y_%m.%d_%H:%M:%S"
CACHEDIR="$XDG_CACHE_HOME/ocr"
if [[ ! -d "$CACHEDIR" ]]; then
    mkdir "$CACHEDIR"
fi

region="$(slurp -w 0 -b '#4c566acc' -s '#ffffff00')"
sleep 0.1

timestamp="$(date +"$DATEFMT")"
imagename="$CACHEDIR/$timestamp.png"
output="$CACHEDIR/$timestamp"

if ! grim -g "$region" "$imagename"; then
    exit
fi

available="$(tesseract --list-langs)"
if ! language="$(wayinput -l -1 -t "Language" -c $available)"; then
    exit
fi
language="${language:-eng}"
tesseract "$imagename" "$output" -l "$language" pdf

if [[ "$1" == "txt" ]]; then
    text="$(pdftotext "$output.pdf" - | tee "$output.txt")"
    response="$(notify-send "Recognized text" "$text" \
        --action=copy="Copy" \
        --action=view="View"\
        --action=pdf="View PDF")"
    case "$response" in
    copy)
        wl-copy <"$output.txt"
        ;;
    view)
        xdg-open "$output.txt"
        ;;
    pdf)
        xdg-open "$output.pdf"
        ;;
    esac
elif [[ "$1" == "pdf" ]]; then
    zathura "$output.pdf"
fi
