#!/bin/sh

if swaymsg -t get_outputs | jq 'map(.power|not)|any' -e; then
    setting=on
else
    setting=off
fi

swaymsg -t get_outputs | jq '.[].name' -r |
    while read -r name; do
        swaymsg output "$name" power "$setting"
    done
