#!/bin/sh

SCREEN="$1"

monitor-sensor |
    awk '$2 == "orientation" { print $4; fflush() }' |
    while read -r orient; do
        case "$orient" in
        normal) transform=0 ;;
        right-up) transform=90 ;;
        bottom-up) transform=180 ;;
        left-up) transform=270 ;;
        esac
        swaymsg output "$SCREEN" transform "$transform"
        eww close bar
        eww open bar
    done
