#!/usr/bin/env bash

DEFAULT_INNER=4
DEFAULT_OUTER=8

target=$1
if [[ -z "$target" ]]; then
    exit
fi
if [[ "$target" == 0 ]]; then
    outer=$DEFAULT_OUTER
    inner=$DEFAULT_INNER
else
    if [[ "$target" == *.* ]]; then
        IFS=. read -r outer inner <<<"$target"
    else
        outer=$target
        inner=$(echo "$target 0.621 / p" | dc)
    fi
fi

swaymsg "gaps outer current set $outer; gaps inner current set $inner"
