# the prompt shown at the top
set promptfmt "\033[97m%d\033[0m%f%S%F" # directory *right* [filter]
set numberfmt "\033[97m" # light gray


# the file info in the bottom left corner:
# size permissions user group link-to
# set statfmt "%S |\033[33m%p |\033[95m%u \033[34m%g |\033[0m-> %l"

# (red) ! message
set errorfmt "\033[31m! %s"

# all: reverse
set cursoractivefmt  "\033[7m"
set cursorparentfmt  "\033[7m"
set cursorpreviewfmt "\033[7m"

# light gray
set borderfmt "\033[97m"

set timefmt        "01. Jan 2006 15:04:05"
set infotimefmtnew "Jan 02 15:04"
set infotimefmtold "06/Jan 02'15"
set tagfmt         "\033[35m"
set selectfmt      "\033[7;90m"

# vim: set ft=lf :
