# leader keys
g ignore
z ignore
Z ignore
\ ignore

q quit
ctrl+c quit 1
Z-Z quit-watch-later
ESC set fullscreen no

MBTN_LEFT     ignore
MBTN_RIGHT    cycle pause
WHEEL_UP   osd-msg  add volume 2
WHEEL_DOWN osd-msg  add volume -2
WHEEL_LEFT    seek -10
WHEEL_RIGHT   seek 10

RIGHT seek  5
LEFT  seek -5
UP    seek  60
DOWN  seek -60

s seek 0 absolute
h seek -5
l seek  5
H seek -60
L seek  60
{ seek -600
} seek  600
; frame-step
, frame-back-step

k osd-msg add volume 2
j osd-msg add volume -2

] add chapter 1
[ add chapter -1

z-s multiply speed 1/1.1
z-f multiply speed 1.1
z-S multiply speed 0.5
z-F multiply speed 2.0

z-l add video-pan-x  0.1
z-h add video-pan-x -0.1
z-j add video-pan-y  0.1
z-k add video-pan-y -0.1
z-i add video-zoom   0.1
z-o add video-zoom  -0.1

z-r add video-rotate 90
z-R set video-rotate 0

Ctrl+WHEEL_UP   script-binding positioning/cursor-centric-zoom
Ctrl+WHEEL_DOWN script-binding positioning/cursor-centric-zoom

# reset view
Ctrl+l set video-zoom 0; no-osd set panscan 0; no-osd set video-pan-x 0; no-osd set video-pan-y 0; no-osd set video-align-x 0; no-osd set video-align-y 0
SPACE cycle pause

> playlist-next
< playlist-prev

Ctrl+g show-progress
i script-binding stats/display-stats-toggle
: script-binding commands/open

z-c add contrast 5
z-C add contrast -5
z-Ctrl+c set contrast 0
z-b add brightness 5
z-B add brightness -5
z-Ctrl+b set brightness 0
z-g add gamma 5
z-G add gamma -5
z-Ctrl+g set gamma 0
z-v add saturation 5
z-V add saturation -5
z-Ctrl+v set saturation 0

t cycle sub-visibility
T cycle secondary-sub-visibility
g-t cycle sub
g-T cycle sub down

g-a cycle audio
g-v cycle video
p screenshot
P screenshot video

g-s add panscan -0.1
g-S add panscan +0.1
g-r cycle-values video-aspect-override "16:9" "4:3" "2.35:1" "no"

M ab-loop

g-d cycle-values hwdec "no" "auto"

\-c script-binding select/select-chapter
\-l script-binding select/select-playlist
\-m script-binding select/menu
\-a script-binding select/select-aid
\-v script-binding select/select-vid
\-t script-binding select/select-track
\-f script-binding select/history
