script-opt='osc-background_color=#eceff4'
script-opt='osc-timecode_color=#2e3440'
script-opt='osc-title_color=#2e3440'
script-opt='osc-time_pos_color=#2e3440'
script-opt='osc-time_pos_outline_color=#eceff4'
script-opt='osc-held_element_color=#D8DEE9'
script-opt='osc-buttons_color=#2e3440'
script-opt='osc-top_buttons_color=#2e3440'
script-opt='osc-small_buttonsL_color=#2e3440'
script-opt='osc-small_buttonsR_color=#2e3440'

osd-back-color='#eceff4'
osd-color='#000000'

script-opt='console-selected_color=#2e3440'
script-opt='console-selected_back_color=#D8DEE9'
script-opt='console-match_color=#ebcb8b'
