hwdec=auto
no-input-default-bindings

ytdl-format=bestaudio+bestvideo[width<=1920]
script-opts=osc-layout=bottombar,osc-seekbarstyle=knob,osc-hidetimeout=1000
script-opt=osc-boxalpha=0
script-opt='osc-background_color=#2e3440'
script-opt='osc-timecode_color=#eceff4'
script-opt='osc-title_color=#eceff4'
script-opt='osc-time_pos_color=#eceff4'
script-opt='osc-held_element_color=#4C566A'
script-opt='osc-buttons_color=#eceff4'
script-opt='osc-small_buttonsL_color=#eceff4'
script-opt='osc-small_buttonsR_color=#eceff4'

profile=box
osd-back-color='#2E3440'
osd-color='#eceff0'
osd-outline-size=0
osd-on-seek=bar

script-opt=console-background_alpha=0
script-opt=console-corner_radius=12
script-opt=console-padding=24
script-opt='console-selected_color=#eceff4'
script-opt='console-selected_back_color=#4C566A'
script-opt='console-match_color=#ebcb8b'
