hwdec=auto
no-input-default-bindings
include=~/.config/mpv/color.conf

ytdl-format=bestaudio+bestvideo[width<=1920]
script-opts=osc-layout=bottombar,osc-seekbarstyle=knob,osc-hidetimeout=1000
script-opt=osc-boxalpha=0

profile=box
osd-outline-size=0
osd-on-seek=bar

script-opt=console-background_alpha=0
script-opt=console-corner_radius=12
script-opt=console-padding=24
