hwdec=auto
no-input-default-bindings=
include=~/.config/mpv/color.conf
save-watch-history=

ytdl-format=bestaudio+bestvideo[width<=1920]
# it does actually jump to the correct video anyways
ytdl-raw-options=yes-playlist=
# script-opts=osc-seekbarstyle=knob,osc-hidetimeout=1000
# script-opt=osc-boxalpha=0

profile=box
osc=no
osd-outline-size=0
osd-on-seek=msg
osd-border-style=background-box

script-opt=console-background_alpha=0
script-opt=console-corner_radius=12
script-opt=console-padding=24
