#!/usr/bin/env bash

function list-in-queue {
    printf $"\0delim\x1f\t\n"
    active="$(mpc -f '%position%' current)"
    while IFS=$'\t' read -r position title artist album; do
        printf "%d %s: %s - %s %s\t" $position "$title" "$artist" "$album"
    done < <(mpc -f $'%position%\t[[%title%]|[%file%]]\t%artist%\t%album%' playlist)
    printf '\0active\x1f%d,\t' "$((active - 1))"
}

if ((ROFI_RETV != 0)); then
    read -r position _ <<<"$1"
    mpc -q play $position
else
    list-in-queue
fi
