# Site-Specific {{{

# The older vector skin works a bit better
[[siteconf]]
url = '^https?://[a-z]+\.wikipedia\.org/wiki/(?!.*useskin=.*)'
rewrite-url = 'x => x.searchParams.append("useskin", "vector")'
# }}}

[start]
startup-script = '''
globalThis.runOnUrl = (command) => () => {
    let link = pager.hoverLink;
    if (link == '') {
        link = pager.buffer.url;
    }
    pager.extern(command + " '" + link + "'", { suspend: false })
}
'''

[buffer]
images = true

[external]
download-dir = "~/Tmp/download/"
history-size = 1024

[status]
format-mode = "overline"     # NOTE: no effect in kitty, which is why I use it
show-cursor-position = false

[display]
highlight-color = "-cha-ansi(yellow)"

[page]
o = "load"
O = "loadEmpty"
go = "loadCursor"

gh = "openHistory"

# Clipboard {{{
'y y' = "copyURL"
'y c' = "copyCursorLink"
'y i' = "copyCursorImage"
'p' = "gotoClipboardURL"
# }}}

x = 'runOnUrl("xdg-open")'
# mpv can handle a lot of web streams (youtube comes to mind), but make sure it opens a window
'X m' = 'runOnUrl("mpv --force-window=immediate")'
'C-w RET' = 'runOnUrl("kitty -e cha")'
'g s' = 'toggleScripting'

'C-k' = '() => pager.load("ddg:")'
'g w' = '() => pager.load("wk:")'
'g d' = '() => pager.load("wd:")'

# Bookmarks {{{
"'" = "gotoMark"
# }}}

[line]
'C-a' = 'line.begin'
'C-o' = 'line.openEditor'
