status_path ~/.local/state/pimsync/status

storage private_remote {
    type caldav
    url https://dav.mailbox.org/
    username {
        cmd pass-get mail/mailbox.org user
    }
    password {
        cmd pass-get mail/mailbox.org .
    }
}

storage private_local {
    type vdir/icalendar
    path ~/cal/private/
}

pair private {
    storage_a private_local
    storage_b private_remote
    collections all
}
