#!/usr/bin/env python

from pathlib import Path
from icalendar import Calendar, Event
import os
from datetime import datetime

CALPATH = os.getenv("HOME") + "/cal/"
ORGPATH = Path(os.getenv("HOME") + "/org/cal/")
if not ORGPATH.is_dir():
    ORGPATH.mkdir()

CALENDARS = [
    "private",
    "uni1",
    "uni2",
]

NOW = datetime.now()

FILE_HEADING_FMT = """#+title: {title}
#+filetags: {tags}
#+author: Exported Automatically

* {title}
/Last synchronised/: {date}
[[{other_file}][Corresponding {other_name} Calendar]]

"""

EVENT_HEADING_FMT = """** {keywd}{title}
{date}
:PROPERTIES:
:CUSTOM_ID: {id}
:END:
{body}
"""


def as_org_date(date: datetime, active) -> str:
    if active:
        return date.strftime("<%Y-%m-%d %a %H:%M>")
    else:
        return date.strftime("[%Y-%m-%d %a %H:%M]")


def as_org_daterange(start: datetime, end: datetime, active) -> str:
    if start.date() == end.date():
        return (
            ("<" if active else "[")
            + start.strftime("%Y-%m-%d %a %H:%M-")
            + end.strftime("%H:%M")
            + (">" if active else "]")
        )
    else:
        return f"{as_org_date(start, active)}--{as_org_date(end, active)}"


def as_org_event(ev: Event, calname) -> (bool, str):
    start: datetime = ev.DTSTART
    end: datetime = ev.DTEND
    in_the_past = end.timestamp() < NOW.timestamp()
    date = as_org_daterange(start, end, not in_the_past)
    body = []
    if (url := ev.get("url")) is not None:
        body.append(f"[[{url}][Url]]")
    body.append("")
    body.append(ev["description"])
    return in_the_past, EVENT_HEADING_FMT.format(
        keywd="DONE " if in_the_past else "",
        title=ev["summary"],
        date=date,
        body="\n".join(body),
        id="cal-" + name + "-" + ev["uid"],
    )


def export_to_org(cal: Calendar, name: str, path: str):
    npath = path + ".org"
    opath = path + "-archive.org"
    with (
        open(npath, "w") as nfile,
        open(opath, "w") as ofile,
    ):
        ofile.write(
            FILE_HEADING_FMT.format(
                title=f"Archive for '{name}'",
                date=as_org_date(NOW, False),
                tags="cal cal-archive",
                other_file=npath,
                other_name="Current",
            )
        )
        nfile.write(
            FILE_HEADING_FMT.format(
                title=f"Calendar '{name}'",
                date=as_org_date(NOW, False),
                tags="cal",
                other_file=opath,
                other_name="Archived",
            )
        )

        events = cal.events
        events.sort(key=lambda e: e.DTSTART)
        for ev in events:
            past, text = as_org_event(ev, name)
            if past:
                ofile.write(text)
            else:
                nfile.write(text)


if __name__ == "__main__":
    for name in CALENDARS:
        dir = Path(CALPATH + name)
        whole = Calendar()
        for file in dir.glob("*/*.ics"):
            cal = Calendar.from_ical(file.read_bytes())
            if len(cal.events) > 0:
                whole.add_component(cal.events[0])
        export_to_org(whole, name, str(ORGPATH.joinpath(name)))
